[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
sha2 = "0.10"
base64 = "0.21"
